name: Issue Template
description: Use this template to submit a request with the required details.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Request Description
        Please provide a clear and concise description of the request.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Enter the details of the request here.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - label: Minor
          value: xp:minor
        - label: Normal
          value: xp:normal
        - label: Major
          value: xp:major
        - label: Critical
          value: xp:critical
    validations:
      required: true

  - type: dropdown
    id: project
    attributes:
      label: Project
      options:
        - label: P:CB
          value: P:CB
        - label: P:DB
          value: P:DB
        - label: P:CORE
          value: P:CORE
        - label: P:PM
          value: P:PM
    validations:
      required: true

  - type: textarea
    id: attachment_notes
    attributes:
      label: Attachments
      description: Add any comments or details about the files you're uploading. Actual files should be attached to the issue after submission.
